version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    ports: 
      - 8080:8080
      - 50000:50000
    volumes: 
      - jenkins-data:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
  
  # jks-slave-jv11:
  #   build: 
  #     context: ./ci-agent
  #     dockerfile: Dockerfile.default
  #   depends_on: 
  #     - jenkins

volumes:
  jenkins-data:
